# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54a4110b7ff4b951ac944465ba4aec57c2622a67275649774255b41196e0ac30ad6fccb3f4a0f3debf65dc01bf5bfe4d5c62f4a77146900e2bc6b0c748dafed0

test:
  secret_key_base: ffc9c0e8f507322e7f71b482f22c63d3b96057e33db41a68c85f36d1b21906c123f99fce0997376b7f419e3fdb62f86f7bf2b9fdc29c0b3a58ef303b57f596a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
